version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
      - "/docs"
      - "/examples/*"
      - "/packages/*"
      schedule:
          interval: 'monthly'
          day: 'wednesday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
