export const listOfAllBluiReactPackages = [
  '@brightlayer-ui/react-native-components',
  '@brightlayer-ui/icons',
  '@brightlayer-ui/icons-svg',
  '@brightlayer-ui/symbols',
  '@brightlayer-ui/react-native-progress-icons',
  '@brightlayer-ui/react-native-vector-icons',
  '@brightlayer-ui/colors',
  '@brightlayer-ui/react-native-themes',
  '@brightlayer-ui/react-native-auth-workflow',
  '@brightlayer-ui/eslint-config',
  '@brightlayer-ui/prettier-config',
  '@brightlayer-ui/cli',
  '@brightlayer-ui/react-native-template-authentication-typescript',
  '@brightlayer-ui/react-native-template-routing-typescript',
  '@brightlayer-ui/react-native-template-blank-typescript',
];
