/**
Copyright (c) 2020-present, Eaton

All rights reserved.

This code is licensed under the BSD-3 license found in the LICENSE file in the root directory of this source tree and at https://opensource.org/licenses/BSD-3-Clause.
**/
export declare const MD3BluiDarkTheme: {
    fonts: import('react-native-paper/lib/typescript/types').MD3Typescale;
    colors: {
        primary: string;
        onPrimary: string;
        primaryContainer: string;
        onPrimaryContainer: string;
        secondary: string;
        onSecondary: string;
        secondaryContainer: string;
        onSecondaryContainer: string;
        tertiary: string;
        onTertiary: string;
        tertiaryContainer: string;
        onTertiaryContainer: string;
        error: string;
        onError: string;
        errorContainer: string;
        onErrorContainer: string;
        background: string;
        onBackground: string;
        surface: string;
        onSurface: string;
        surfaceVariant: string;
        onSurfaceVariant: string;
        outline: string;
        outlineVariant: string;
        shadow: string;
        scrim: string;
        inverseSurface: string;
        inverseOnSurface: string;
        inversePrimary: string;
        elevation: {
            level0: string;
            level1: string;
            level2: string;
            level3: string;
            level4: string;
            level5: string;
        };
        surfaceDisabled: string;
        onSurfaceDisabled: string;
        backdrop: string;
        primaryNonText: string;
        errorNonText: string;
        disabled: string;
        warning: string;
        warningNonText: string;
        onWarning: string;
        warningContainer: string;
        onWarningContainer: string;
        success: string;
        successNonText: string;
        onSuccess: string;
        successContainer: string;
        onSuccessContainer: string;
        orange: string;
        orangeNonText: string;
        onOrange: string;
        orangeContainer: string;
        onOrangeContainer: string;
        purple: string;
        purpleNonText: string;
        onPurple: string;
        purpleContainer: string;
        onPurpleContainer: string;
        surfaceContainerLowest: string;
        surfaceContainerLow: string;
        surfaceContainer: string;
        surfaceContainerHigh: string;
        surfaceContainerHighest: string;
        disabledContainer: string;
        onDisabledContainer: string;
        sliderTrack: string;
        sliderTrackDisabled: string;
        errorFilledContainer: string;
        onErrorFilledContainer: string;
        errorShadedContainer: string;
        onErrorShadedContainer: string;
        errorOutlinedContainerOutline: string;
        onErrorOutlinedContainerOutline: string;
        orangeFilledContainer: string;
        onOrangeFilledContainer: string;
        orangeShadedContainer: string;
        onOrangeShadedContainer: string;
        orangeOutlinedContainer: string;
        onOrangeOutlinedContainer: string;
        warningFilledContainer: string;
        onWarningFilledContainer: string;
        warningShadedContainer: string;
        onWarningShadedContainer: string;
        warningOutlinedContainerOutline: string;
        onWarningOutlinedContainer: string;
        successFilledContainer: string;
        onSuccessFilledContainer: string;
        successShadedContainer: string;
        successShadedLabel: string;
        successOutlinedContainerOutline: string;
        onSuccessOutlinedContainer: string;
        primaryFilledContainer: string;
        onPrimaryFilledContainer: string;
        primaryShadedContainer: string;
        onPrimaryShadedContainer: string;
        primaryOutlinedContainerOutline: string;
        onPrimaryOutlinedContainer: string;
        purpleFilledContainer: string;
        onPurpleFilledContainer: string;
        purpleShadedContainer: string;
        onPurpleShadedContainer: string;
        purpleOutlinedContainerOutline: string;
        onPurpleOutlinedContainer: string;
        neutralFilledContainer: string;
        onNeutralFilledContainer: string;
        neutralShadedContainer: string;
        onNeutralShadedContainer: string;
        neutralOutlinedContainerOutline: string;
        onNeutralOutlinedContainer: string;
        textFieldContainer: string;
        progressBarTrackOnStatusFilledContainer: string;
        mapTextOutline: string;
    };
    dark: boolean;
    mode?: 'adaptive' | 'exact';
    roundness: number;
    animation: {
        scale: number;
        defaultAnimationDuration?: number;
    };
    version: 3;
    isV3: true;
};
