name: Publish Auth Workflow

on:
  push:
    branches: [ "dev", "master" ]
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  publish_auth_workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') }}
    strategy:
      matrix:
        node-version: [20.x]
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download workflow dist
        uses: actions/download-artifact@v4
        with:
          name: workflow-dist
          path: packages/auth-workflows/workflow-dist
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn --immutable
        working-directory: packages/auth-workflows
      - run: npm run publish:package -- -b ${{env.BRANCH}}
        working-directory: packages/auth-workflows