name: PR Actions
on:
    pull_request_target:
        types:
            - opened

permissions:
    pull-requests: write
    contents: read

jobs:
    pr-labels:
        name: PR Labels
        uses: etn-ccis/blui-automation/.github/workflows/blui-labels.yml@dev
        secrets: inherit

    pr-comment:
        name: PR Comment
        uses: etn-ccis/blui-automation/.github/workflows/blui-comment.yml@dev
        secrets: inherit
