name: Build

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']
    pull_request_target:
        types:
            - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn prettier:check
            # - run: yarn lint

    # unit_tests_components:
    #     runs-on: ubuntu-latest

    #     strategy:
    #         matrix:
    #             node-version: [20.x]

    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #               cache: 'yarn'
    #         - run: yarn install --immutable
    #         - run: yarn coverage
    #           working-directory: packages/blui-react-native-component-library
    #         - name: Upload to Codecov
    #           uses: codecov/codecov-action@v5
    #           with:
    #               token: ${{ secrets.CODECOV_TOKEN }}
    #               directory: packages/blui-react-native-component-library/coverage/
    #               files: cobertura-coverage.xml
    #               flags: component-tests
    #               name: codecov-report
    #               verbose: true

    build_components_library:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn install --immutable
            - run: yarn build
              working-directory: packages/blui-react-native-component-library
            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: lib-dist
                  if-no-files-found: error
                  path: packages/blui-react-native-component-library/dist

    build_theme_verify_artifacts:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn build --base=${{env.base-href}}
              working-directory: docs
            - name: Save dist
              uses: actions/upload-artifact@v4
              with:
                  name: theme-dist
                  if-no-files-found: error
                  path: docs/dist

    # unit_tests_workflows:
    #     runs-on: ubuntu-latest
    #     strategy:
    #         matrix:
    #             node-version: [18.x]

    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v4
    #           with:
    #               name: docs
    #               path: docs/dist
    #         - name: deploy
    #           uses: JamesIves/github-pages-deploy-action@v4
    #           with:
    #               token: ${{ secrets.CODECOV_TOKEN }}
    #               directory: packages/auth-workflows/coverage/
    #               files: clover.xml
    #               flags: login-wf-tests
    #               name: codecov-report
    #               verbose: true

    build_login_workflow:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
              working-directory: packages/auth-workflows
            - run: yarn build
              working-directory: packages/auth-workflows
            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: workflow-dist
                  if-no-files-found: error
                  path: packages/auth-workflows/dist

    build_rn_progress_icons:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn install --immutable
            - run: yarn build
              working-directory: packages/progress-icons
            - name: Save rn progress icon build
              uses: actions/upload-artifact@v4
              with:
                  name: progress-icon-dist
                  if-no-files-found: error
                  path: packages/progress-icons/dist

    build_rn_docs:
        runs-on: ubuntu-latest
        needs: build_theme_verify_artifacts
        strategy:
            matrix:
                node-version: [20.x]
        env:
            base-href: ${{ github.ref == 'refs/heads/master' && '/react-native/' || '/react-native-dev/' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - name: Download rn theme build
              uses: actions/download-artifact@v4
              with:
                  name: theme-dist
                  if-no-files-found: error
                  path: packages/themes/dist
            - run: yarn test
              working-directory: packages/themes

    unit_tests_components:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn install --immutable
            - run: yarn coverage
              working-directory: packages/component-library
            - name: Upload to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: packages/component-library/coverage/
                  files: cobertura-coverage.xml
                  flags: component-tests
                  name: codecov-report
                  verbose: true

    build_components_library:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn build
              working-directory: packages/component-library
            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: lib-dist
                  if-no-files-found: error
                  path: packages/component-library/dist
    # keep publishing steps at end of workflow

    publish-templates:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-templates.yml@dev
        secrets: inherit
        needs: prettier_lint

    publish-components:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-components.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_components_library]

    publish-auth-workflow:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-auth-workflow.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_login_workflow]

    publish-progress-icons:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-progress-icons.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_rn_progress_icons]

    publish-themes:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-themes.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_theme_verify_artifacts]
