name: Build

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']
    pull_request_target:
        types:
            - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn prettier:check
            # - run: yarn lint

    build_rn_progress_icons:
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            node-version: [18.x]
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - run: yarn install --immutable
            - run: yarn build
              working-directory: packages/progress-icons
            - name: Save rn progress icon build
              uses: actions/upload-artifact@v4
              with:
                  name: progress-icon-dist
                  if-no-files-found: error
                  path: packages/progress-icons/dist

    build_rn_docs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
        env:
            base-href: ${{ github.ref == 'refs/heads/master' && '/react-native/' || '/react-native-dev/' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn build --base=${{env.base-href}}
              working-directory: docs
            - name: Save dist
              uses: actions/upload-artifact@v4
              with:
                  name: docs
                  if-no-files-found: error
                  path: docs/dist

    deploy_rn_docs_dev:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        needs: build_rn_docs
        env:
            DEV_DEPLOY_TOKEN: ${{secrets.DEV_DEPLOY_TOKEN}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download build
              uses: actions/download-artifact@v4
              with:
                  name: docs
                  path: docs/dist
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist/docs
                  token: ${{env.DEV_DEPLOY_TOKEN}}
                  repository-name: brightlayer-ui-components/react-native-dev
                  branch: master
                  git-config-name: Brightlayer UI Agent
                  git-config-email: brightlayer-ui@eaton.com
                  commit-message: 'Automated deployment to GitHub Pages ${{github.sha}}'

    deploy_rn_docs_prod:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        needs: build_rn_docs
        env:
            DEV_DEPLOY_TOKEN: ${{secrets.DEV_DEPLOY_TOKEN}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download build
              uses: actions/download-artifact@v4
              with:
                  name: docs
                  path: dist/docs
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist/docs
                  token: ${{env.DEV_DEPLOY_TOKEN}}
                  repository-name: brightlayer-ui-components/react-native
                  branch: master
                  git-config-name: Brightlayer UI Agent
                  git-config-email: brightlayer-ui@eaton.com
                  commit-message: 'Automated deployment to GitHub Pages ${{github.sha}}'

    build_theme_verify_artifacts:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn build
              working-directory: packages/themes
            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: theme-dist
                  if-no-files-found: error
                  path: packages/themes/dist
            - run: yarn test
              working-directory: packages/themes

    # keep publishing steps at end of workflow
    publish-templates:
      uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-templates.yml@dev
      secrets: inherit
      needs: prettier_lint

    publish-components:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-components.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_components_library]

    publish-auth-workflow:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-auth-workflow.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_login_workflow]

    publish-progress-icons:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-progress-icons.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_rn_progress_icons]

    publish-themes:
        uses: etn-ccis/blui-react-native/.github/workflows/blui-publish-themes.yml@dev
        secrets: inherit
        needs: [prettier_lint, build_theme_verify_artifacts]